### ISSUE TITLE
Application crashing after inputting user data with console errors

### ISSUE THREAD

**Issue by michaelsmoody** [stt-datacore/website#352]
(Let me preface this with saying thank you, I've been using the tool for a _very long time_, probably 18-24 months at this point, and I've contributed to the previous desktop-based applications and various forks that might have been its predecessor - IAmPicard. I would love to contribute, but recently, between many demands on my time, I have had limited opportunity to do so)

The console errors are:

```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'content_type')
    at ue (events.ts:28:18)
    at voyagecalculator.tsx:857:25
    at lt (voyagecalculator.tsx:817:3)
    at ro (react-dom.production.min.js:157:137)
    at Hu (react-dom.production.min.js:267:460)
    at Pi (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at xi (react-dom.production.min.js:250:138)
    at vi (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
uu @ react-dom.production.min.js:216
a.componentDidCatch.n.callback @ react-dom.production.min.js:217
fa @ react-dom.production.min.js:131
hu @ react-dom.production.min.js:220
zi @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ti @ react-dom.production.min.js:252
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
fi @ react-dom.production.min.js:237
No @ react-dom.production.min.js:170
(anonymous) @ voyagecalculator.tsx:95
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
d @ voyagecalculator.tsx:21
(anonymous) @ voyagecalculator.tsx:21
dt @ voyagecalculator.tsx:28
ro @ react-dom.production.min.js:157
Hu @ react-dom.production.min.js:267
Pi @ react-dom.production.min.js:250
_i @ react-dom.production.min.js:250
xi @ react-dom.production.min.js:250
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
fi @ react-dom.production.min.js:237
No @ react-dom.production.min.js:170
onInitialize @ playertools.tsx:380
(anonymous) @ storage.ts:53
Promise.then (async)
(anonymous) @ storage.ts:51
Di @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
F @ scheduler.production.min.js:16
w.port1.onmessage @ scheduler.production.min.js:12

react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'content_type')
    at ue (events.ts:28:18)
    at voyagecalculator.tsx:857:25
    at lt (voyagecalculator.tsx:817:3)
    at ro (react-dom.production.min.js:157:137)
    at Hu (react-dom.production.min.js:267:460)
    at Pi (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at xi (react-dom.production.min.js:250:138)
    at vi (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
uu @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
fa @ react-dom.production.min.js:131
hu @ react-dom.production.min.js:220
zi @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ti @ react-dom.production.min.js:252
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
fi @ react-dom.production.min.js:237
No @ react-dom.production.min.js:170
(anonymous) @ voyagecalculator.tsx:95
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
d @ voyagecalculator.tsx:21
(anonymous) @ voyagecalculator.tsx:21
dt @ voyagecalculator.tsx:28
ro @ react-dom.production.min.js:157
Hu @ react-dom.production.min.js:267
Pi @ react-dom.production.min.js:250
_i @ react-dom.production.min.js:250
xi @ react-dom.production.min.js:250
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
fi @ react-dom.production.min.js:237
No @ react-dom.production.min.js:170
onInitialize @ playertools.tsx:380
(anonymous) @ storage.ts:53
Promise.then (async)
(anonymous) @ storage.ts:51
Di @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
F @ scheduler.production.min.js:16
w.port1.onmessage @ scheduler.production.min.js:12

events.ts:28 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'content_type')
    at ue (events.ts:28:18)
    at voyagecalculator.tsx:857:25
    at lt (voyagecalculator.tsx:817:3)
    at ro (react-dom.production.min.js:157:137)
    at Hu (react-dom.production.min.js:267:460)
    at Pi (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at xi (react-dom.production.min.js:250:138)
    at vi (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
ue @ events.ts:28
(anonymous) @ voyagecalculator.tsx:857
lt @ voyagecalculator.tsx:817
ro @ react-dom.production.min.js:157
Hu @ react-dom.production.min.js:267
Pi @ react-dom.production.min.js:250
_i @ react-dom.production.min.js:250
xi @ react-dom.production.min.js:250
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
fi @ react-dom.production.min.js:237
No @ react-dom.production.min.js:170
(anonymous) @ voyagecalculator.tsx:95
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
d @ voyagecalculator.tsx:21
(anonymous) @ voyagecalculator.tsx:21
dt @ voyagecalculator.tsx:28
ro @ react-dom.production.min.js:157
Hu @ react-dom.production.min.js:267
Pi @ react-dom.production.min.js:250
_i @ react-dom.production.min.js:250
xi @ react-dom.production.min.js:250
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
fi @ react-dom.production.min.js:237
No @ react-dom.production.min.js:170
onInitialize @ playertools.tsx:380
(anonymous) @ storage.ts:53
Promise.then (async)
(anonymous) @ storage.ts:51
Di @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
F @ scheduler.production.min.js:16
w.port1.onmessage @ scheduler.production.min.js:12
```

Unfortunately, that prevents complete use of all tools, and the application is completely blank. I have tested an alternative user (a family member), and their user data functions without issue, at least at the moment, as they have a currently running voyage.

I'm unsure what exactly is causing the issue, at least, at the moment, but I figured the first thing to do would be to open an issue. I might be able to dig into it later, but, step one, open GitHub issue with the errors to capture them.

**Comment by michaelsmoody** [comment]
Intriguingly, after retrieving rewards from both an event and the "whatever they call them" mini accomplishment challenges, the error is now clear.

In looking at my user json, I'm looking at the differences.....

**Comment by michaelmoodyconsensus** [comment]
This seems to relate to the content of the event. `content_type` being shuttles. I haven't examined the full json of the before and after, but this is my first glance analysis. Retrieving the rewards for the event removed this from the json entirely.
