### ISSUE TITLE
Finished voyage data is not shown

### ISSUE THREAD

**Issue by diegonoya** [stt-datacore/website#385]
Since Jun 22 on the DataCore's website, a finished voyage data is not processed correctly. Some errors are shown in the browser's dev console:

react-dom.production.min.js:216 TypeError: o[e.type] is not a function
    at voyagestats.tsx:550:62
    at Array.map (<anonymous>)
    at n._renderRewards (voyagestats.tsx:536:15)
    at n.render (voyagestats.tsx:644:38)
    at Wo (react-dom.production.min.js:187:188)
    at Bo (react-dom.production.min.js:186:173)
    at Hu (react-dom.production.min.js:269:427)
    at Pi (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at xi (react-dom.production.min.js:250:138)
uu @ react-dom.production.min.js:216
a.componentDidCatch.n.callback @ react-dom.production.min.js:217
fa @ react-dom.production.min.js:131
hu @ react-dom.production.min.js:220
zi @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ti @ react-dom.production.min.js:252
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
fi @ react-dom.production.min.js:237
No @ react-dom.production.min.js:170
(anonymous) @ voyagecalculator.tsx:118
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
p @ voyagecalculator.tsx:24
(anonymous) @ voyagecalculator.tsx:24
Mt @ voyagecalculator.tsx:31
ro @ react-dom.production.min.js:157
Hu @ react-dom.production.min.js:267
Pi @ react-dom.production.min.js:250
_i @ react-dom.production.min.js:250
xi @ react-dom.production.min.js:250
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
Di @ react-dom.production.min.js:263
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
F @ scheduler.production.min.js:16
w.port1.onmessage @ scheduler.production.min.js:12
react-dom.production.min.js:216 TypeError: o[e.type] is not a function
    at voyagestats.tsx:550:62
    at Array.map (<anonymous>)
    at n._renderRewards (voyagestats.tsx:536:15)
    at n.render (voyagestats.tsx:644:38)
    at Wo (react-dom.production.min.js:187:188)
    at Bo (react-dom.production.min.js:186:173)
    at Hu (react-dom.production.min.js:269:427)
    at Pi (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at xi (react-dom.production.min.js:250:138)
uu @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
fa @ react-dom.production.min.js:131
hu @ react-dom.production.min.js:220
zi @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ti @ react-dom.production.min.js:252
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
fi @ react-dom.production.min.js:237
No @ react-dom.production.min.js:170
(anonymous) @ voyagecalculator.tsx:118
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
p @ voyagecalculator.tsx:24
(anonymous) @ voyagecalculator.tsx:24
Mt @ voyagecalculator.tsx:31
ro @ react-dom.production.min.js:157
Hu @ react-dom.production.min.js:267
Pi @ react-dom.production.min.js:250
_i @ react-dom.production.min.js:250
xi @ react-dom.production.min.js:250
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
Di @ react-dom.production.min.js:263
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
F @ scheduler.production.min.js:16
w.port1.onmessage @ scheduler.production.min.js:12
voyagestats.tsx:550 Uncaught (in promise) TypeError: o[e.type] is not a function
    at voyagestats.tsx:550:62
    at Array.map (<anonymous>)
    at n._renderRewards (voyagestats.tsx:536:15)
    at n.render (voyagestats.tsx:644:38)
    at Wo (react-dom.production.min.js:187:188)
    at Bo (react-dom.production.min.js:186:173)
    at Hu (react-dom.production.min.js:269:427)
    at Pi (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at xi (react-dom.production.min.js:250:138)
(anonymous) @ voyagestats.tsx:550
n._renderRewards @ voyagestats.tsx:536
n.render @ voyagestats.tsx:644
Wo @ react-dom.production.min.js:187
Bo @ react-dom.production.min.js:186
Hu @ react-dom.production.min.js:269
Pi @ react-dom.production.min.js:250
_i @ react-dom.production.min.js:250
xi @ react-dom.production.min.js:250
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
fi @ react-dom.production.min.js:237
No @ react-dom.production.min.js:170
(anonymous) @ voyagecalculator.tsx:118
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
p @ voyagecalculator.tsx:24
(anonymous) @ voyagecalculator.tsx:24
Mt @ voyagecalculator.tsx:31
ro @ react-dom.production.min.js:157
Hu @ react-dom.production.min.js:267
Pi @ react-dom.production.min.js:250
_i @ react-dom.production.min.js:250
xi @ react-dom.production.min.js:250
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
Di @ react-dom.production.min.js:263
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Oi @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
F @ scheduler.production.min.js:16
w.port1.onmessage @ scheduler.production.min.js:12

**Comment by jdarcy2012** [comment]
I have observed this in Chrome 102 and 103 for PC, Edge (Chrome) 103, most recent Chrome for Android.
